# Generated by Django 5.2.4 on 2026-07-02 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Buy/Long'), ('SELL', 'Sell/Short')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=25)),
                ('fees', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('pnl', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('exchange_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchanges.exchangeaccount')),
            ],
        ),
    ]
