# Generated by Django 5.2.4 on 2026-07-02 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=20)),
                ('wallet_type', models.CharField(choices=[('SPOT', 'Spot'), ('FUTURES', 'Futures/Derivatives')], default='SPOT', max_length=10)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=30)),
                ('usd_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='exchanges.exchangeaccount')),
            ],
            options={
                'unique_together': {('exchange_account', 'asset', 'wallet_type')},
            },
        ),
    ]
